### ISSUE TITLE
[Feature] Support for annotate_template_file_names

### ISSUE THREAD

**Issue by tom-lord** [haml/haml-rails#172]
There is a new (unreleased) feature in the rails master branch: [`config.action_view.annotate_template_file_names`](https://github.com/rails/rails/pull/38848).

However, this only adds support for erb templates.

It would be nice to prepare support for this feature, which will likely be shipped with rails `6.1.0`, in the haml-rails library too.
The HAML template engine generates the output [here](https://github.com/haml/haml/blob/598f2b3a364b5601c844db79bf04b387061a396d/lib/haml/temple_engine.rb#L68-L83), but presumably it should be this library's responsibility to read the rails-specific configuration parameter (so generated HTML appends/prepends the rendered partial name).

**Comment by ConfusedVorlon** [comment]
just to add
- this feature [did ship in 6.1](https://blog.saeloun.com/2020/05/11/rails-support-annotates-html-output-with-template-file-names.html)
- It is awesome!
- I just switched to haml (which I _love_) and losing this annotation is the first significant downside

I'd love to see support added in haml.

thank you

**Comment by hcatlin** [comment]
I think we can definitely prioritize this!

**Comment by dmarcoux** [comment]
There's an open PR for this: https://github.com/haml/haml/pull/1050.

Since this issue's creation, the configuration was renamed to `annotate_rendered_view_with_filenames` in Rails [a673ce6](https://github.com/rails/rails/pull/39204/commits/a673ce69e758b36739964589cd2d39304cd1c593).

**Comment by dmarcoux** [comment]
The PR I linked in my previous comment is now merged, so this is now supported.

**Comment by ConfusedVorlon** [comment]
Awesomeness. Thank you :)

**Comment by hcatlin** [comment]
https://github.com/haml/haml/releases/tag/v5.2.2
