### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by yamakamineyu** [haml/haml-rails#173]
# IPアドレス
54.249.255.249

**Comment by mo1015** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
**※今後実装に関する質問がありましたら、メンターに確認をお願いします！**

**Comment by yhara** [comment]
Seems like a programming school student happened to send their homework here, instead of their repository?

@mo1015 [こっち](https://github.com/yamakamineyu/chat-space/issues)に貼ってもらうつもりでしたかね… 😅
